# 参考
# https://yutaro-blog.net/2021/04/29/docker-laravel-vuejs-2/
# https://yutaro-blog.net/2021/04/30/docker-laravel-vuejs-3/
# https://zenn.dev/re24_1986/articles/b76c3fd8f76aec
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: main
      TZ: "Asia/Tokyo"
    ports:
      - 5433:5432 #MySQLと違うので注意
    volumes:
      - ./docker-config/postgres/data:/var/lib/postgresql/data
      - ./docker-config/postgres/logs:/var/log