# 参考
# https://yutaro-blog.net/2021/04/29/docker-laravel-vuejs-2/
# https://yutaro-blog.net/2021/04/30/docker-laravel-vuejs-3/
version: '3.8'

# volumes:
#   mysql-volume:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html
    # environment:
    #   - DB_CONNECTION=mysql
    #   - DB_HOST=db
    #   - DB_PORT=3306
    #   - DB_DATABASE=${DB_NAME}
    #   - DB_USERNAME=${DB_USER}
    #   - DB_PASSWORD=${DB_PASSWORD}

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html

  # postgres:
  #   image: postgres:14.5-bullseye
  #   container_name: my_postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  #     - ./init:/docker-entrypoint-initdb.d

  # postgres:
  #   container_name: postgres_container
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
  #     PGDATA: /data/postgres
  #   volumes:
  #      - postgres:/data/postgres
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - postgres
  #   restart: unless-stopped

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #      - pgadmin:/var/lib/pgadmin

  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - postgres
  #   restart: unless-stopped

  # db:
  #   build:
  #     context: .
  #     dockerfile: ./docker/mysql/Dockerfile
  #   ports:
  #     - ${DB_PORT}:3306
  #   environment:
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #     TZ: 'Asia/Tokyo'
  #   volumes:
  #     - mysql-volume:/var/lib/mysql












# version: '3'
# services:
#   # web:
#   #   build: ./docker/web
#   #   container_name: web
#   #   volumes:
#   #     - ./app:/var/www/html
#   #     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#   #   ports:
#   #     - "80:80"
#   nginx:
#     build: ./nginx
#     container_name: nginx
#     depends_on:
#       - server
#     ports:
#       - 8080:80
#   server:
#     build: ./server
#     container_name: server
